[package]
name = "aptos-coins"
version = "1.0.0"
authors = []

[addresses]
MyAddr ='859424fae76eec6b82dd4d0b5579950abc67298976eae2bbafad94ed56cda9b5'
Std = "0x1"
aptos_std = "0x1"
[dev-addresses]



[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
